# 배포 전 로컬 개발환경에서 컨테이너 테스트를 위한 Docker Compose 설정입니다.
version: '3.8'

services:
  backend:
    build: ./backend
    container_name: sag_portal_backend
    ports:
      - "5001:5000" # 호스트 포트 5001번을 컨테이너 5000번 포트와 연결
    # 로컬 개발 시 코드 변경을 즉시 반영하기 위해 volumes를 활성화합니다.
    volumes:
      - ./backend:/app
    # 로컬 개발 시에는 Gunicorn 대신 Flask의 내장 개발 서버를 사용해 핫 리로딩을 활성화합니다.
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build: ./frontend
    container_name: sag_portal_frontend
    ports:
      # Vite 개발 서버의 기본 포트인 5173을 호스트의 8050 포트와 연결합니다.
      - "8050:5173"
    depends_on:
      - backend
    # 프론트엔드 핫 리로딩을 위해 소스 코드를 마운트하고 개발 서버를 실행합니다.
    volumes:
      # 소스 코드는 호스트와 동기화합니다.
      - ./frontend:/app
      # node_modules는 컨테이너 내부에 유지하여 호스트의 빈 폴더로 덮어쓰는 것을 방지합니다.
      - /app/node_modules
    command: npm run dev -- --host
