services:
  backend:
    build: ./backend
    container_name: sag_portal_backend
    environment:
      - MSSQL_SERVER=172.16.220.3
      - MSSQL_DATABASE=SAG
      - MSSQL_USER=seokgyun
      - MSSQL_PASSWORD=1q2w3e4r
      - MSSQL_PORT=1433
    ports:
      - "5001:5001" # 호스트 포트 5001번을 컨테이너 5001번 포트와 연결
    # 로컬 개발 시 코드 변경을 즉시 반영하기 위해 volumes를 활성화합니다.
    volumes:
      - ./backend:/app
    # 로컬 개발 시에는 Gunicorn 대신 Flask의 내장 개발 서버를 사용해 핫 리로딩을 활성화합니다.
    command: flask run --host=0.0.0.0 --port=5001

  frontend:
    build:
      context: ./frontend
      # 로컬 개발 시에는 Dockerfile의 'build-stage'까지만 사용합니다.
      target: build-stage
    container_name: sag_portal_frontend
    ports:
      # Vite 개발 서버의 기본 포트인 5173을 호스트의 5173 포트와 연결합니다.
      - "5173:5173"
    depends_on:
      - backend
    # 프론트엔드 핫 리로딩을 위해 소스 코드를 마운트하고 개발 서버를 실행합니다.
    volumes:
      # 소스 코드는 호스트와 동기화합니다.
      - ./frontend:/app
      # node_modules는 컨테이너 내부에 유지하여 호스트의 빈 폴더로 덮어쓰는 것을 방지합니다.
      - /app/node_modules
    environment:
      - DOCKER_DEV=true
    command: npm run dev -- --host
