version: '3.8'

services:
  backend:
    # build 대신 Docker Hub의 이미지를 직접 사용합니다.
    image: ${DOCKER_REGISTRY}/sag-portal-backend:${IMAGE_TAG}
    container_name: sag_portal_backend
    ports:
      - "5001:5000"
    restart: always # 컨테이너가 예기치 않게 종료되면 자동으로 재시작합니다.

  frontend:
    image: ${DOCKER_REGISTRY}/sag-portal-frontend:${IMAGE_TAG}
    container_name: sag_portal_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always